### ISSUE TITLE
TypeError: r.isUnstyled is not a function

### ISSUE THREAD

**Issue by mmgolden** [primefaces/primevue#7748]
### Describe the bug

After upgrading to v4.3.3, we are now seeing "TypeError: r.isUnstyled is not a function" in our Sentry issues. It looks like it's coming from the `_loadThemeStyles()` function.

<img width="1283" alt="Image" src="https://github.com/user-attachments/assets/a3c559cd-b182-4733-99cd-79cee01b9eec" />

### Reason for not contributing a PR

- [x] Lack of time
- [x] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/primevue-4-vite-issue-template-puiej3fd?file=README.md

### Environment

OS: Windows >=10
Browser: Chrome 90.0.4430

### Vue version

3.5.13

### PrimeVue version

4.3.3

### Node version

22.14.0

### Browser(s)

Chrome 90.0.4430

### Steps to reproduce the behavior

Unable to reproduce

### Expected behavior

There should not be a type error for the `isUnstyled()` function.

**Comment by cagataycivici** [comment]
Please try with 4.3.5 and create a new ticket if issue persists.
