### ISSUE TITLE
Dialog: Uncaught TypeError: getComputedStyle is not a function

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#4312]
### Describe the bug

![image](https://github.com/primefaces/primevue/assets/16963395/5fbafa3a-bfb0-4cc8-9327-93acf60e32d9)

 var getComputedStyle = getComputedStyle(_this2.container);

![image](https://github.com/primefaces/primevue/assets/16963395/d620abb7-8a2d-4031-97fb-3ffacecd1fff)

Drag window and error

on 3.30.0 work

### Reproducer

no

### PrimeVue version

3.32.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by melloware** [comment]
Hmm looks SSR related?  https://stackoverflow.com/questions/68995581/why-getcomputedstyle-method-does-not-work-properly-in-my-nuxt-app

**Comment by melloware** [comment]
Introduced with https://github.com/primefaces/primevue/pull/4252

**Comment by Dmytro-Lukashenko** [comment]
Hi guys! I've fixed this bug. It was the incorrect naming of the variable. I've changed getComputedStyle to containerComputedStyle. @melloware could you please check it?
