### ISSUE TITLE
Primevue 2.4 TabView and Accordeon throw errow on npm build

### ISSUE THREAD

**Issue by zsuzsmuzs** [primefaces/primevue#1019]
SyntaxError: primevue\tabview\TabView.vue: Unexpected token (67:12)

```
  65 |     render() {
  66 |         return (
> 67 |             <div class="p-tabview p-component">
     |             ^
  68 |                 {this.$slots.default}
  69 |                 <ul ref="nav" class="p-tabview-nav" role="tablist">
  70 |                     {
```

**Comment by tugcekucukoglu** [comment]
Please try again adding babel.config.js

```
module.exports = {
    presets: ["@vue/app"]
};
```

**Comment by zsuzsmuzs** [comment]
Thanks, for the suggestion. I put the babel.config.js in the root folder of my project and I am getting this error now:

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@vue/babel-preset-app' from ...

**Comment by bdbusch** [comment]
I get the same problem. Added the preset didn't help. 

        '@vue/cli-plugin-babel/preset',

was already in the array - either adding the @vue/app or only providing @vue/app didn't help. 

reverting back.

**Comment by M-erb** [comment]
Same issues with 2.4.0 using the Accordion component. Reverting to 2.3.0 is the only thing that fixed the issue

**Comment by zsuzsmuzs** [comment]
I finally managed to get it working. 
However both the Accordion and the TabView components are very bug-ridden. I already spent hours to get my code working in v2.4. but I fear I have to revert to 2.3.0 again. :(
Not happy atm...

**Comment by balance80** [comment]
> I finally managed to get it working.
> However both the Accordion and the TabView components are very bug-ridden. I already spent hours to get my code working in v2.4. but I fear I have to revert to 2.3.0 again. :(
> Not happy atm...

Exact same problem here, I had to revert back to 2.3.0 where everything is working as expected.

**Comment by juanparati** [comment]
I also experiencing the same issue.
It seems that TabView v2.4 was written using the Vue 3.x style.

The following error is received:

```
Module parse failed: Unexpected token (67:12)
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     render() {
|         return (
>             <div class="p-tabview p-component">
|                 {this.$slots.default}
|                 <ul ref="nav" class="p-tabview-nav" role="tablist">
 @ ./node_modules/primevue/tabview/TabView.vue?vue&type=script&lang=js& 1:0-109 1:125-128 1:130-236 1:130-236
 @ ./node_modules/primevue/tabview/TabView.vue

```

I am using Laravel-mix.

**Comment by zsuzsmuzs** [comment]
It is possible to get it working with Laravel-mix. Just add the following lines in the webpack.mix.js

 mix.webpackConfig({module: {
      rules: [{
        test: /\.js?$/,
        use: [{
          loader: 'babel-loader',
          options: {
            presets: ["@vue/app"]
          }
        }]
      }]
    }})

Maybe I had to install this package as well, but not sure about it: @vue/babel-preset-app

However with the v2.4 there were major issues with vuejs reactivity. Components which are reactive with 2.3 are not with 2.4 anymore. :( I hope there will be a solution soon.

**Comment by tugcekucukoglu** [comment]
I cloned [primevue-quickstart](https://github.com/primefaces/primevue-quickstart) and created [this repo](https://github.com/tugcekucukoglu/primevue-v2-jsx).  I didn't get any error. How can I replicate the issue? What should I change?
